# Generated by Django 3.1.5 on 2021-02-03 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Tovar alohida rasmlari')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Taglar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tovar nomi')),
                ('slug', models.SlugField(verbose_name='*')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Rasmi')),
                ('description', models.TextField(blank=True, verbose_name='Tovar haqida')),
                ('price', models.PositiveIntegerField(default=0, null=True, verbose_name='Narxi')),
                ('old_price', models.PositiveIntegerField(blank=True, default=0, verbose_name='Avvalgi Narxi')),
                ('colors', models.CharField(max_length=50, verbose_name='Ranglari')),
                ('instock', models.BooleanField(default=True, verbose_name="Omborda bor yoki yo'q")),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='shop.categories')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.tag')),
            ],
            options={
                'verbose_name': 'Tovar',
                'verbose_name_plural': 'Tovarlar',
            },
        ),
    ]
