# Generated by Django 3.1.5 on 2021-02-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ismi')),
                ('email', models.EmailField(max_length=224, verbose_name='Email')),
                ('title', models.CharField(max_length=150, verbose_name='Mavzu')),
                ('comment', models.TextField(verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Muhokama',
                'verbose_name_plural': 'Muhokamalar',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ismi')),
                ('email', models.EmailField(max_length=224, verbose_name='Email')),
                ('title', models.CharField(max_length=150, verbose_name='Mavzu')),
                ('comment', models.TextField(verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Aloqa',
                'verbose_name_plural': 'Aloqalar',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=550, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='*')),
                ('image', models.ImageField(upload_to='blog_images/', verbose_name='Poster')),
                ('author', models.CharField(blank=True, default='Admin', max_length=50, verbose_name='Muallif')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
    ]
