# Generated by Django 3.1.5 on 2021-02-05 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_comment_contact_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categories', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Kategoriya osti Kategoriya',
                'verbose_name_plural': 'Kategoriya osti Kategoriyalar',
                'ordering': ['name'],
            },
        ),
    ]
