# Generated by Django 3.1.5 on 2021-02-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productimages_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'Tovar rasmlari', 'verbose_name_plural': 'Tovar rasmlari'},
        ),
        migrations.AddField(
            model_name='categories',
            name='hot',
            field=models.BooleanField(default=False, verbose_name='Mashxur'),
        ),
    ]
