# Generated by Django 3.1.5 on 2021-02-10 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210210_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_title', models.CharField(max_length=50, verbose_name='Brand nomi')),
                ('brand_desc', models.CharField(max_length=200, verbose_name='Brand haqida')),
                ('brand_poster', models.ImageField(upload_to='posters/', verbose_name='Brand poster')),
                ('brand_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.tag')),
            ],
            options={
                'verbose_name': 'Slayder',
                'verbose_name_plural': 'Slaydlar',
            },
        ),
    ]
