# Generated by Django 3.1.7 on 2021-02-22 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0011_auto_20210212_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('tm_id', models.CharField(max_length=50, verbose_name='tm_id')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('province', models.CharField(max_length=50, verbose_name='Province')),
                ('district', models.CharField(max_length=50, verbose_name='District')),
                ('street', models.CharField(max_length=50, verbose_name='Street')),
                ('residence_address', models.CharField(max_length=50, verbose_name='Home_adress')),
                ('postal_code', models.PositiveIntegerField(verbose_name='Postal_code')),
                ('payment_type', models.CharField(choices=[('cash', 'CASH'), ('click', 'CLICK'), ('PayMe', 'PAYME'), ('oson', 'OSON')], max_length=50, verbose_name='Payment_type')),
                ('payed', models.BooleanField(default=False, verbose_name='Payed')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-id'],
            },
        ),
    ]
